### ISSUE TITLE
Rename zhanghai.me.transparentbar.gschema.xml

### ISSUE THREAD

**Issue by zhanghai** [lamarios/gnome-shell-extension-transparent-top-bar#1]
Could you rename `zhanghai.me.transparentbar.gschema.xml`? Since this fork is not authored by me, I don't think it should use my (domain) name. A better name might be `com.ftpix.transparentbar.gschema.xml`.

**Comment by lamarios** [comment]
sure will work on it, sorry I only saw it now,

**Comment by lamarios** [comment]
done in new version
