### ISSUE TITLE
Icon Background Not Transparent.

### ISSUE THREAD

**Issue by ayxsth** [lamarios/gnome-shell-extension-transparent-top-bar#10]
The background of the top right icons is not transparent.
Here's the screenshot for your referenece.
![image](https://user-images.githubusercontent.com/49949471/167066185-cc9c33aa-69c1-490b-8989-1de79c0cda68.png)

**Comment by lamarios** [comment]
Distribution ? Gnome version? Wayland or X11? Are you using any shell theme? What extensions are you using you using? Nvidia GPU?

**Comment by ayxsth** [comment]
Distro: Pop!_OS
Gnome Version: 42.0
X11
Nope, not any shell themes.
I didn't get the extension thing. Can you clear me out?
Yes, NVIDIA GPU.

**Comment by lamarios** [comment]
I mean do you use any other extensions alongside this one?

**Comment by ayxsth** [comment]
> I mean do you use any other extensions alongside this one?

For making the top transparent? Or for any other use?

If it's for other use, yes. I have been using other extensions, but if it's for making the top transparent, no.

**Comment by Noobsai** [comment]
I think I have the same problem. The shadow is very strong:
![Screenshot from 2022-05-08 15-36-50](https://user-images.githubusercontent.com/17625194/167292358-d367fe19-f4e2-47b5-bb93-e2dccae56a74.png) ![Screenshot from 2022-05-08 15-36-26](https://user-images.githubusercontent.com/17625194/167292354-8dea06d8-8987-44f0-b4a0-c621458c58e5.png)
 I adjusted the CSS so it looks like:
![Screenshot from 2022-05-08 15-48-16](https://user-images.githubusercontent.com/17625194/167292684-ce3e2fc3-8a69-4bf2-9f05-6186e65ded31.png) ![Screenshot from 2022-05-08 15-37-20](https://user-images.githubusercontent.com/17625194/167292551-0c4c287f-0d49-465e-ac19-30302a4da2df.png)

@ayxsth, maybe the background of your icons is the icon shadow. Perhaps the icons don't have a transparent background. Try fixing CSS first or changing the icon pack.

Changed CSS lines: 1141, 1148, 1165.
Changes https://github.com/Noobsai/gnome-shell-extension-transparent-top-bar/commit/458806f9f0ee45b422818e40581942023cd7de79

**Comment by lamarios** [comment]
I'll be on gnome 42 very soon using Fedora so it'll be a stock implementation. I'll check it then.

**Comment by mikoducky** [comment]
> I think I have the same problem. The shadow is very strong: ![Screenshot from 2022-05-08 15-36-50](https://user-images.githubusercontent.com/17625194/167292358-d367fe19-f4e2-47b5-bb93-e2dccae56a74.png) ![Screenshot from 2022-05-08 15-36-26](https://user-images.githubusercontent.com/17625194/167292354-8dea06d8-8987-44f0-b4a0-c621458c58e5.png) I adjusted the CSS so it looks like: ![Screenshot from 2022-05-08 15-48-16](https://user-images.githubusercontent.com/17625194/167292684-ce3e2fc3-8a69-4bf2-9f05-6186e65ded31.png) ![Screenshot from 2022-05-08 15-37-20](https://user-images.githubusercontent.com/17625194/167292551-0c4c287f-0d49-465e-ac19-30302a4da2df.png)
> 
> @ayxsth, maybe the background of your icons is the icon shadow. Perhaps the icons don't have a transparent background. Try fixing CSS first or changing the icon pack.
> 
> Changed CSS lines: 1141, 1148, 1165. Changes [Noobsai@458806f](https://github.com/Noobsai/gnome-shell-extension-transparent-top-bar/commit/458806f9f0ee45b422818e40581942023cd7de79)

This did not work for me. When I make some of your changes, the smart opaque stops working. If I make all your changes, I get an error, attached.

![image](https://user-images.githubusercontent.com/74574472/167327574-0a86dc19-469a-4094-a698-47528b1836f6.png)

**Comment by Henry-Hiles** [comment]
> I think I have the same problem. The shadow is very strong: ![Screenshot from 2022-05-08 15-36-50](https://user-images.githubusercontent.com/17625194/167292358-d367fe19-f4e2-47b5-bb93-e2dccae56a74.png) ![Screenshot from 2022-05-08 15-36-26](https://user-images.githubusercontent.com/17625194/167292354-8dea06d8-8987-44f0-b4a0-c621458c58e5.png) I adjusted the CSS so it looks like: ![Screenshot from 2022-05-08 15-48-16](https://user-images.githubusercontent.com/17625194/167292684-ce3e2fc3-8a69-4bf2-9f05-6186e65ded31.png) ![Screenshot from 2022-05-08 15-37-20](https://user-images.githubusercontent.com/17625194/167292551-0c4c287f-0d49-465e-ac19-30302a4da2df.png)
> 
> @ayxsth, maybe the background of your icons is the icon shadow. Perhaps the icons don't have a transparent background. Try fixing CSS first or changing the icon pack.
> 
> Changed CSS lines: 1141, 1148, 1165. Changes [Noobsai@458806f](https://github.com/Noobsai/gnome-shell-extension-transparent-top-bar/commit/458806f9f0ee45b422818e40581942023cd7de79)

i have the same issue. could your fix please be merged in?
