### ISSUE TITLE
A black underline when opacity is not 0%

### ISSUE THREAD

**Issue by Yestercafe** [lamarios/gnome-shell-extension-transparent-top-bar#19]
opacity 0%:
![Screenshot from 2023-07-24 10-43-55](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar/assets/25558466/7ff17a6a-b5b3-474d-9e44-4aa5580f8f57)

opacity 1%:
![Screenshot from 2023-07-24 10-43-41](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar/assets/25558466/de4d3a81-45cc-4306-ac94-762eb3449322)

opacity 25%:
![Screenshot from 2023-07-24 10-44-04](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar/assets/25558466/35f9b6e0-ac7a-42dd-9860-5ee9100add53)

I always got a black underline/shadow when the top bar opacity is not set to 0%, like the screenshots above.

My OS is Fedora 38, GNOME version is 44.3, windowing system is Wayland, Linux kernel version is 6.4.4. And I have disabled all of the other extensions.

I found all settings about shadow in CSS file were set to 0, but the line just exists. What can I do to fix this?

**Comment by stuarthayhurst** [comment]
This seems to be related upstream https://github.com/zhanghai/gnome-shell-extension-transparent-top-bar/commit/59c32ae1323f4666c8c1d5b0e85f10c7e1e2a332

Maybe it could be applied here?

**Comment by lamarios** [comment]
most likely I'll try to find time to fix it.  PRs welcomed otherwise :)

**Comment by lamarios** [comment]
submitted the fix to extensions.gnome.org
