### ISSUE TITLE
DING prevents transparancy from working on Gnome 40

### ISSUE THREAD

**Issue by ServerBBQ** [lamarios/gnome-shell-extension-transparent-top-bar#2]
On Gnome 40, whenever [DING](https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/) is active, the top bar stays opaque

One workaround is to disable the option "Opaque top bar when a window touches it".

I tested: Endeavor os(hardware), and Fedora(vm)

**Comment by lamarios** [comment]
I sorry, I can't make sure that this extension is compatible with every other extension, that would be a hell to maintain given the very little time to maintain this I have.
