### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [lamarios/gnome-shell-extension-transparent-top-bar#20]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by yochananmarqos** [comment]
FYI, zhangai [added support](https://github.com/zhanghai/gnome-shell-extension-transparent-top-bar/commit/b18ef51d2f6ce42931384f996db1be32f34bdefd).

**Comment by lamarios** [comment]
Looks fairly easy. Thanks. I'll have a look when time allows.

**Comment by lamarios** [comment]
it's actually a bit more complicated than expected. I need to redo the settings, docs are not very good and testing is a pain for gnome extensions

**Comment by lamarios** [comment]
[Screencast from 2023-09-26 19-04-04.webm](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar/assets/1192563/027adeda-11ab-4778-bd47-1664ddd79d32)

**Comment by lamarios** [comment]
Submitted to the extension website
