### ISSUE TITLE
Will work with Gnome 42.9?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [lamarios/gnome-shell-extension-transparent-top-bar#22]
Will work with Gnome 42.9?

**Comment by lamarios** [comment]
This is not a valid gnome version.

**Comment by Jibun-no-Kage** [comment]
Well... it is what is installed on my Linux box right now!  So I am not sure how you define it as invalid?  I built the system yesterday with the latest available Ubuntu Jammy Jelllfish image.

\# cat /etc/os-release
PRETTY_NAME="Armbian 23.8.3 jammy"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
PRIVACY_POLICY_URL="https://www.armbian.com"
UBUNTU_CODENAME=jammy
ARMBIAN_PRETTY_NAME="Armbian 23.8.3 jammy"

![Screenshot from 2023-10-18 23-00-55](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar/assets/96628648/7551b018-76b7-465c-a8ae-9a3f935b980c)

**Interesting thing is... I did install it, using the extension manager, and it seems to work.**

**Comment by lamarios** [comment]
yeah there was a compatible version for gnome 42.  This extension started at gnome 3.38 if i remember properly.
