### ISSUE TITLE
GNOME 46.1 support

### ISSUE THREAD

**Issue by JPLeBreton** [lamarios/gnome-shell-extension-transparent-top-bar#24]
Just upgraded from 45 to 46.1 and it disabled extension for compat reasons. Hopefully as simple as updating a number in the manifest.

**Comment by JPLeBreton** [comment]
Tried updating the version # to 46 in metadata.json and now I see this error:
```
Error: no signal 'actor-added' on object 'MetaWindowGroup'
```

**Comment by lamarios** [comment]
45 to 46 has breaking changes. You need to update the extension to the latest version.
