### ISSUE TITLE
Support for Gnome 47

### ISSUE THREAD

**Issue by valerybaturin** [lamarios/gnome-shell-extension-transparent-top-bar#25]
Extension does not work with Gnome 47

**Comment by idoric** [comment]
A useful resource: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html).

**Comment by lamarios** [comment]
thanks, will look into it when I have time, hopefully this week end

**Comment by lamarios** [comment]
extension submitted to gnome extensions
