### ISSUE TITLE
gnome 41 it does not work

### ISSUE THREAD

**Issue by sephid86** [lamarios/gnome-shell-extension-transparent-top-bar#3]
hi.

First. 
Thank you for making such a great program.
I really like this program

I want this program to work in gnome 41.

how long do i have to wait?

Sorry for my poor English.

This is using a translator.

**Comment by Dorro101** [comment]
Hi

I also would love to see an update, just upgraded to Fedora 35. Using the original extension, but prefer the settings available in your version!

Ciao
Dorian

**Comment by lamarios** [comment]
Update for gnome 41 pending review
