### ISSUE TITLE
opacity of top bar and corner do not match

### ISSUE THREAD

**Issue by schlauerlauer** [lamarios/gnome-shell-extension-transparent-top-bar#6]
Hi! thanks for making this extension,
I've noticed a bug with the newest version (shell version 41):

the top bar opacity doesn't seem to match the rounded corner opacity:

![Bildschirmfoto vom 2021-11-16 15-41-24](https://user-images.githubusercontent.com/40915271/142006451-7f2afdb9-b8e6-4cfa-99b7-f6f220503852.png)

**Comment by lamarios** [comment]
Thanks for reporting it. I'll have a look once I've got a bit of time.

**Comment by lamarios** [comment]
This one is a bit more tricky than what I originally thought. Which actually can be seen from your screen that the corner part and the top bar overlap which mean opacity will always be darker on the overlapping area. I tried to move the corner down a bit but it looks kinda weird and It looks like Gnome shell doesn't allow the clip css properties (or I'm not using it properly).

The easiest solution would be to remove those rounded corners but it might not please everyone haha.

**Comment by schlauerlauer** [comment]
Looks like they got it working:
https://github.com/zhanghai/gnome-shell-extension-transparent-top-bar/issues/11 :slightly_smiling_face:

**Comment by lamarios** [comment]
Oh great. I'll have a look. Thanks.
