### ISSUE TITLE
Bar wouldn't stay transparent 100% of the time.

### ISSUE THREAD

**Issue by mikejaques** [lamarios/gnome-shell-extension-transparent-top-bar#7]
Using a new install of Pop!_OS 21.10, sometimes the bar would revert to opaque, even if it was set to completely transparent, and even if it the switch was set to stay the same, even if a window butts up against it.  I can't really pin down any more specific behaviour than that.

I installed it via the URL: https://extensions.gnome.org/extension/3960/transparent-top-bar-adjustable-transparency/

And toggled the off to on. Initially it worked after a reboot, but quickly it fell into the above behaviour with taking windows into and out of maximize/restore stated.

I'd love for this to work consistently because its such a clean look when it is working.

**Comment by lamarios** [comment]
Hmm, 

I tried to reproduce it on Fedora which use vanilla gnome and I can't. It can be an issue with Pop Os theme or any conflict with some other extensions you might have installed.

**Comment by mikejaques** [comment]
I haven't installed any other extensions, but as is well known, Pop!_OS wraps a lot of their own pre-built extensions and modifications on top of gnome so much that they refer to it as "Cosmic DE", so that's probably the likely culprit.

**Comment by Akmal02** [comment]
Yep can confirm that the transparency doesn't work after a while in Pop!_OS 21.10. However it did used to work without issues on 21.04.

**Comment by aquatix** [comment]
I have exactly the same issue; is there something we can do to get a trace for example?

**Comment by lamarios** [comment]
This is a bit hard for me to debug as I don't use pop os. It's probably some sort of conflict between pop os changes to gnome shell (or extension) and this one.

**Comment by aquatix** [comment]
I get a bunch of these when looking at `journalctl -e /usr/bin/gnome-shell`:

```
Jan 03 14:30:20 asuka gnome-shell[3406]: JS ERROR: TypeError: this._windowSignalIds.get(...) is undefined
                                         _onWindowActorRemoved@/home/mbscholt/.local/share/gnome-shell/extensions/transparent-top-bar@ftpix.com/extension.js:112:54
                                         on_window_create/<@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1220:32
                                         _initializeUI/<@resource:///org/gnome/shell/ui/main.js:257:16
```

**Comment by dantahoua** [comment]
I confirm it is not working on my Pop Os 21.10 machine but great on my Fedora 35 machine. Maybe we should write also to the Pop Os github...

**Comment by lamarios** [comment]
My guess would be that pop os is using an extension to change their top bar color which would interfere with this one or use some or using a CSS with !important ?

**Comment by bodhi-alt** [comment]
I have this problem as well. PopOS 21.10. Every time the screen is locked or a screensaver starts the bar loses it's transparency. I can consistently fix it with a reboot or by running "r" in alt+F2, so rebooting the shell.

**Comment by dantahoua** [comment]
For now I edited with
`
sudo gedit /usr/share/themes/Pop-dark/gnome-shell/gnome-hell.css
`
and I replaced #000 on line 1209 with rgba(0,0,0,0); (Search for #panel in the search box).

**Comment by aquatix** [comment]
A few hours ago I updated a bunch of Pop packages, including the shell and such, and it seems the issue has gone - at least after locking the screen. I will report back when I have tested a bit more.

**Comment by lamarios** [comment]
Awesome, thanks for reporting.

**Comment by bodhi-alt** [comment]
The updates also fixed it for me on my laptop and main pc.

**Comment by mikejaques** [comment]
So far, so good, looks to be fixed.  I'm going to close the issue as it looks like whatever patches Pop_OS released as aquatix mentioned above, might have fixed it.  Cheers and thanks for a really classy, polished, and clean looking extension.
