### ISSUE TITLE
Top Bar Ubuntu 22.04 Wayland

### ISSUE THREAD

**Issue by verndog** [lamarios/gnome-shell-extension-transparent-top-bar#9]
Tried all info requested. Still no Top Bar Transparency.

**Comment by johndzxu** [comment]
Also looking for wayland support here. This doesn't work on wayland but wayland is becoming the default windows manager.

**Comment by lamarios** [comment]
strange, it could be because of ubuntu distro is also applying css to the shell theme. I have two machines on upstream gnome and it work both on X11 and wayland.

**Comment by johndzxu** [comment]
I just found the culprit, which is ubuntu's builtin gnome extension [Desktop Icon NG], when I turn it off the extension works. Can we fix it here or do I need to open an issue there?
 (https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/)

**Comment by lamarios** [comment]
Good catch. I think someone complained about this a while ago on gnome extension website. I don't think there's much I cna do though.

If you uncheck the opaque top bar when a window application touches it does the bar go transparent.

**Comment by johndzxu** [comment]
Yes it does.

**Comment by lamarios** [comment]
That's an issue with the desktop icon extension that make the shell believe something is touching the top bar.

**Comment by rastersoft** [comment]
Hi, I'm the creator of Desktop Icons ND (DING). Unfortunately, under Wayland, there aren't thinks like a "Desktop window" or similar, so I had to use several tricks to emulate a desktop with icons. But fortunately I think that there is a way of solving this: in Wayland, no application can set the "skip_from_window_list" flag, which is mandatory for things like a desktop window. But an extension can set it under some very specific circumstances (which were put there specifically for DING, BTW). So a solution is to check if we are under Wayland AND a window has the "skip_from_window_list" flag set, and in that case put the background transparent.

What do you think?

**Comment by lamarios** [comment]
Hey,
Thanks for reaching out! 

That sounds like a good idea. Unfortunately I must admit I have a very hard time understanding gnome API (this extension is just a fork of someone else's work) do you have some link for documentation  on where I could check for both these things?

**Comment by rastersoft** [comment]
I sent a patch just now.

**Comment by skoruppa** [comment]
Can confirm that provided patch fixed the issue :)

**Comment by lamarios** [comment]
Thanks!

I'll have a look tomorrow.

**Comment by lamarios** [comment]
Reviewed and looks good. Submitted the extension for review.
